"""Modelos SQLAlchemy compartilhados pela aplicacao."""

# Registra primeiro as tabelas referenciadas por ForeignKey nos demais modelos.
from app.auth import models as _auth_models  # noqa: F401
from app.models import references as _references  # noqa: F401
from app.models.agenda import (
    Convite,
    Evento,
    EventoLideranca,
    EventoParticipante,
    InsightEvento,
    LembreteEvento,
    PautaEvento,
    PresencaEvento,
    StatusEvento,
    TipoEvento,
)
from app.models.arquivo import Anexo, Arquivo, DocumentoExtraido, TipoAnexo
from app.models.cadastro import (
    Eleitor,
    Endereco,
    EstadoCivil,
    Lideranca,
    Pessoa,
    PessoaContato,
    PessoaDocumento,
    PessoaEndereco,
)
from app.models.cadastro_relacoes import (
    Comunidade,
    HierarquiaLideranca,
    Indicacao,
    NucleoFamiliar,
    PessoaComplementoPolitico,
    PessoaComunidade,
    PessoaMerge,
    PessoaNucleoFamiliar,
    PessoaPessoaTipo,
    PessoaRedeSocial,
    PessoaTag,
    PessoaTipo,
    RelacionamentoPessoa,
    SuspeitaDuplicidade,
    Tag,
    ValidacaoCadastro,
)
from app.models.comunicacao import CanalComunicacao, Interacao, TipoInteracao
from app.models.dashboard import (
    DashboardConfiguracao,
    Indicador,
    IndicadorValor,
    Relatorio,
    RelatorioExecucao,
)
from app.models.etl import (
    ErroImportacao,
    FonteDado,
    Importacao,
    ImportacaoArquivo,
    ImportacaoLinha,
    JobProcessamento,
    LogProcessamento,
    RegraDeduplicacao,
    ResultadoDeduplicacao,
    StagingPessoa,
)
from app.models.global_refs import CategoriaDataComemorativa, DataComemorativa
from app.models.metas import (
    AcompanhamentoMeta,
    AlertaMeta,
    MetaVoto,
    MetaVotoAlvo,
    PeriodoMeta,
    RankingLideranca,
    TipoMetaVoto,
)
from app.models.territorio import (
    Bairro,
    Estado,
    Geocodificacao,
    LiderancaTerritorio,
    LocalVotacao,
    Municipio,
    PessoaTerritorio,
    SecaoEleitoral,
    Territorio,
    TerritorioHierarquia,
    TipoTerritorio,
    ZonaEleitoral,
)

__all__ = [
    "Anexo",
    "Arquivo",
    "DocumentoExtraido",
    "TipoAnexo",
    "Convite",
    "Evento",
    "EventoLideranca",
    "EventoParticipante",
    "InsightEvento",
    "LembreteEvento",
    "PautaEvento",
    "PresencaEvento",
    "StatusEvento",
    "TipoEvento",
    "Eleitor",
    "Endereco",
    "EstadoCivil",
    "Comunidade",
    "HierarquiaLideranca",
    "Indicacao",
    "Lideranca",
    "NucleoFamiliar",
    "Pessoa",
    "PessoaComplementoPolitico",
    "PessoaComunidade",
    "PessoaContato",
    "PessoaDocumento",
    "PessoaEndereco",
    "PessoaNucleoFamiliar",
    "PessoaMerge",
    "PessoaPessoaTipo",
    "PessoaRedeSocial",
    "PessoaTag",
    "PessoaTipo",
    "RelacionamentoPessoa",
    "SuspeitaDuplicidade",
    "Tag",
    "ValidacaoCadastro",
    "CanalComunicacao",
    "Interacao",
    "TipoInteracao",
    "CategoriaDataComemorativa",
    "DataComemorativa",
    "ErroImportacao",
    "FonteDado",
    "Importacao",
    "ImportacaoArquivo",
    "ImportacaoLinha",
    "JobProcessamento",
    "LogProcessamento",
    "RegraDeduplicacao",
    "ResultadoDeduplicacao",
    "StagingPessoa",
    "DashboardConfiguracao",
    "Indicador",
    "IndicadorValor",
    "Relatorio",
    "RelatorioExecucao",
    "Bairro",
    "Estado",
    "Geocodificacao",
    "LiderancaTerritorio",
    "LocalVotacao",
    "Municipio",
    "PessoaTerritorio",
    "SecaoEleitoral",
    "Territorio",
    "TerritorioHierarquia",
    "TipoTerritorio",
    "ZonaEleitoral",
    "AcompanhamentoMeta",
    "AlertaMeta",
    "MetaVoto",
    "MetaVotoAlvo",
    "PeriodoMeta",
    "RankingLideranca",
    "TipoMetaVoto",
]
