OPENAPI_TAGS = [
    {"name": "Infraestrutura", "description": "Disponibilidade e dependencias da API."},
    {"name": "Tenants", "description": "Gestao das unidades de isolamento do SaaS."},
    {"name": "Autenticacao", "description": "Login, sessao e identidade atual."},
    {"name": "Usuarios", "description": "Usuarios, perfis e permissoes do tenant."},
    {"name": "Publico", "description": "Planos, leads e contratacoes do site publico."},
    {"name": "Cadastro", "description": "Pessoas, eleitores e liderancas."},
    {"name": "Territorio", "description": "Territorios e georreferenciamento."},
    {"name": "Metas", "description": "Metas, votos e indicadores."},
    {"name": "Eleicoes", "description": "Catalogo global de eleicoes oficiais."},
    {"name": "Importacao e ETL", "description": "Importacoes, staging e qualidade."},
    {"name": "Agenda", "description": "Agenda e eventos."},
    {"name": "Demandas", "description": "Demandas e atendimentos."},
    {"name": "Comunicacao", "description": "Interacoes, canais e relacionamento."},
    {"name": "Dashboard", "description": "Dashboards e relatorios."},
]
