"""Schemas Pydantic compartilhados pela aplicacao."""

from app.schemas.cadastro import (
    EleitorCreate,
    EleitorResponse,
    EleitorUpdate,
    EnderecoCreate,
    EnderecoResponse,
    EnderecoUpdate,
    LiderancaCreate,
    LiderancaResponse,
    LiderancaUpdate,
    PessoaContatoCreate,
    PessoaContatoResponse,
    PessoaContatoUpdate,
    PessoaCreate,
    PessoaDocumentoCreate,
    PessoaDocumentoResponse,
    PessoaDocumentoUpdate,
    PessoaEnderecoCreate,
    PessoaEnderecoResponse,
    PessoaEnderecoUpdate,
    PessoaResponse,
    PessoaUpdate,
)

__all__ = [
    "EleitorCreate",
    "EleitorResponse",
    "EleitorUpdate",
    "EnderecoCreate",
    "EnderecoResponse",
    "EnderecoUpdate",
    "LiderancaCreate",
    "LiderancaResponse",
    "LiderancaUpdate",
    "PessoaContatoCreate",
    "PessoaContatoResponse",
    "PessoaContatoUpdate",
    "PessoaCreate",
    "PessoaDocumentoCreate",
    "PessoaDocumentoResponse",
    "PessoaDocumentoUpdate",
    "PessoaEnderecoCreate",
    "PessoaEnderecoResponse",
    "PessoaEnderecoUpdate",
    "PessoaResponse",
    "PessoaUpdate",
]
